### ISSUE TITLE
FR: Stereo mode

### ISSUE THREAD

**Issue by daxliniere** [JanosGit/Schrammel_OJD#45]
Hi Janos,
It would be great if you could add a stereo mode switch to your great OJD plugin.
I'll often use it on a stereo pair of guitars and currently it means making adjustments to both while tweaking the sound.

I'm fully aware this will double CPU usage, but clearly no worse than 2 separate instances.

Also, the bypass button is pretty tiny. Would you consider making a larger target, please? (Or if you want to keep the GUi the same, perhaps also add the 'power LED' as a hit area for the bypass switch.)

All the best,
Dax.

**Comment by JanosGit** [comment]
Hi, 

I‘m not sure if I understand your request correctly. The latest release of the plugin works as stereo plugin when loaded on a stereo track and as a mono plugin when loaded onto a mono track. Are you refering to something different? What would that stereo switch do?

Regarding the button, I have no plans to change the user interface design. Increasing the hit area could be an option though, but I can‘t give you an estimate when I‘ll find time for that. However, I‘m always open for pull requests, so feel free to implement it yourself 🙂

**Comment by daxliniere** [comment]
Hey Janos, Thanks for the reply.
When I give this plugin a stereo input (from two hard-panned guitar DI signals) it produces a mono output. Does that clarify?
EDIT: Perhaps I'm running an earlier version? I've had it in my plugins folder for some time now.

I wish I knew how to program, otherwise I would make the PR. Maybe I'll took a look at the code and see if I can work it out. ;)

All the best!
Dax.

**Comment by JanosGit** [comment]
Hey Dax,

if you click on the little gear icon in the top right corner you should see a view like this:

<img width="329" alt="Screenshot 2023-12-05 at 19 38 36" src="https://github.com/JanosGit/Schrammel_OJD/assets/13800135/d529c807-c14b-4a73-b299-b8eaac6305e6">

What version & git commit does yours report? In case you don't find a gear icon there, you definitively have an older version. In that case, please update to version 0.9.8, you find the download links for the installers [on the releases page](https://github.com/JanosGit/Schrammel_OJD/releases/tag/0.9.8) or on my website.

In case you are running version 0.9.8 and the issue still persists, could you give me a bit more information about the DAW, operating system and plugin format (VST3 or AU) that you are using so that I can try to reproduce the issue myself?

If you are no programmer I doubt that looking at the code will really lead you anywhere quickly, but I don't want to demotivate you :) I'll see if I find some spare time for updates in January otherwise

**Comment by daxliniere** [comment]
I downloaded and checked again, but there was still no gear icon. Hmmm... Ahh! Your website still points to 0.9.6!

**Comment by daxliniere** [comment]
Yes, I can see the gear icon in v0.9.8 and stereo mode. Fantastic! Thanks Janos!

Can you confirm this new version will produce identical results when recalling a session made with 0.9.6?

**Comment by JanosGit** [comment]
Oh wow, good spot, I migrated the website to a new host recently, seems like I might have migrated an old version of the website pointing to an older release. I'll fix that! But glad stereo is now working for you as expected. The new version will sound the same when recalling a session stored with the old version. Only the default parameters applied when creating a fresh instance have changed slightly.

**Comment by daxliniere** [comment]
Thanks, Janos!

**Comment by daxliniere** [comment]
Oops, I re-opened this issue because the stereo situation is not solved in 0.9.8.

Test procedure:
1) Take 2 mono tracks and pan them hard left/right
2) Insert OJD onto each of them with identical settings
3) Feed them into a folder/buss/etc
4) Insert OJD onto the folder track and bypass it
5) Hit play and listen, then bypass the individual instances and unbypass the buss instance.

= The sound is dramatically different. The buss version is 5.4dB quieter on the left channel and the signal is definitely not stereo.

I'm not sure what's going on, but the pedal is not acting as dual mono (i.e. two identical algorithms with linked control parameters).
